   - chroots:
                - chroot:
                    name: "root"
   - packages:
                - package:
                    name: "root"
                    packagefile: "packages.txt"
                - package:
                    name: "yay"
                    install: "yay -Syu --noconfirm"
                    packagefile: "yay.txt"
                - package:
                    name: "wayland"
                    install: "yay -Syu --noconfirm"
                    packagefile: "wayland.txt"
   - scripts:
                - script:
                    name: "root"
                    file: "rootinstall.sh"
                - script:
                    name: "userinstall"
                    file: "userinstall.sh"
                - script:
                    name: "yayinstall"
                    file: "yayinstall.sh"
execution:
 - partitiontable: "#disk#"
 - format: "#disk#"
 - mount: "#disk#"
 - bootstrap:
 - fstab:
 - chroot:
    user: "root"
    steps:
      - systemsetup:
      - createuser: "#user#" # set this to the name of your user
      - packages: "root"
      - script: "root"
      - bootloader: "#disk#" # device name of your disk
 - chroot:
    user: "#user#"
    steps:
      - script: "yayinstall"
      - packages: "yay"
      - packages: "wayland"
      - script: "userinstall"
